spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:XE
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: NOTICE
        password: 0911

    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 50MB
